title: "Mike Rouse - Unity Developer"
description: "Gameplay • Tools • C# • VR"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

search: true
lunr:
  search_within_pages: true

collections:
  projects:
    output: true
    permalink: /projects/:name/
  systems:
    output: true
    permalink: /systems/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
  - scope:
      path: ""
      type: "systems"
    values:
      layout: single
  - scope:
      path: ""
    values:
      layout: single
