title: "Mike Rouse - Unity Developer"
description: "Gameplay • Tools • C# • VR"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

url: "https://mike-rouse.github.io"
baseurl: "" 

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

sass:
  style: compressed
include:
  - assets/css

search: true
lunr:
  search_within_pages: true

defaults:
  - scope:
      path: ""
    values:
      layout: single
